---
- name: Install and configure tools
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Install snapd
      apt:
        name: snapd
    - name: Install unzip
      apt:
        name: unzip
    - name: Install net-tools
      apt:
        name: net-tools
    - name: Create mellonaut user
      lineinfile:
        path: /etc/sudoers
        line: "mellonaut ALL=(ALL) NOPASSWD:ALL"
        state: present
    - name: Install apt-transport-https, ca-certificates, and gnupg
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
    - name: Install ffuf
      apt:
        name: ffuf
    - name: Install flameshot
      apt:
        name: flameshot
    - name: Install eyewitness, bloodhound, hurl
      apt:
        name:
          - eyewitness
          - bloodhound
          - hurl
    - name: Install ncat
      apt:
        name: ncat
    - name: Install rlwrap
      apt:
        name: rlwrap
    - name: Install dirsearch
      apt:
        name: dirsearch
    - name: Install socat
      apt:
        name: socat
    - name: Install remmina
      apt:
        name: remmina
    - name: Install docker.io and docker-compose
      apt:
        name:
          - docker.io
          - docker-compose
    - name: Install feroxbuster
      apt:
        name: feroxbuster
    - name: Install golang
      apt:
        name: golang-1.19-go
        state: present
    - name: Install Python3-pip, pipx, and python3-venv
      apt:
        name:
          - python3-pip
          - pipx
          - python3-venv
        state: present
    - name: Git clone Certipy
      git:
        repo: https://github.com/ly4k/Certipy.git
        dest: /etc/ansible/Certipy
    - name: Install Certipy
      command: pip3 install /etc/ansible/Certipy
    - name: Install mitm6
      command: pip install mitm6
    # - name: Install Cherrytree
    #   apt:
    #     name: cherrytree
    #     state: present




# Playbook2 starts here

    # - name: Download and install CrackMapExec
    #   get_url:
    #     url: https://github.com/Porchetta-Industries/CrackMapExec/releases/download/v5.3.0/cme-ubuntu-latest-3.10.zip
    #     dest: /usr/bin
    #   unarchive:
    #     src: /usr/bin/cme-ubuntu-latest-3.10.zip
    #     dest: /usr/bin
    #     remote_src: yes
    # - name: Download and install cmedb
    #   get_url:
    #     url: https://github.com/Porchetta-Industries/CrackMapExec/releases/download/v5.3.0/cmedb-ubuntu-latest-3.10.zip
    #     dest: /usr/bin
    #   unarchive:
    #     src: /usr/bin/cmedb-ubuntu-latest-3.10.zip
    #     dest: /usr/bin
    #     remote_src: yes      
    # - name: Install Python3-pip, pipx, and python3-venv
    #   apt:
    #     name:
    #       - python3-pip
    #       - pipx
    #       - python3-venv
    # - name: Install Python3-pip, pipx, and python3-venv
    #   apt:
    #     name:
    #       - python3-pip
    #       - pipx
    #       - python3-venv    
    # - name: Install pipx and ensurepath
    #   command:
    #     - python3 -m pip install pipx
    #     - python3 -m pipx ensurepath    
    # - name: Git clone Certipy
    #   git:
    #     repo: https://github.com/ly4k/Certipy.git
    #     dest: /etc/ansible/Certipy    
    # - name: Install Certipy
    #   command: pip3 install /etc/ansible/Certipy    
    # - name: Install mitm6
    #   command: pip install mitm6    
    # - name: Git clone Pretender
    #   git:
    #     repo: https://github.com/RedTeamPentesting/pretender.git
    #     dest: /etc/ansible/pretender    
    # - name: Build and install Pretender
    #   command:
    #     - cd /etc/ansible/pretender
    #     - go build
    #     - mv pretender /usr/bin    
    # - name: Install Cherrytree
    #   apt:
    #     name: cherrytree    
    # - name: Git clone PwnCat
    #   git:
    #     repo: https://github.com/calebstewart/pwncat.git
    #     dest: /opt/pwncat    
    # - name: Install PwnCat
    #   command:
    #     - cd /opt/pwncat
    #     - python3 setup.py install    
    # - name: Create PwnDrop directory
    #   file:
    #     path: /pwndrop
    #     state: directory    
    # - name: Download and install PwnDrop
    #   get_url:
    #     url: https://github.com/kgretzky/pwndrop/releases/download/1.0.1/pwndrop-linux-amd64.tar.gz
    #     dest: /pwndrop    
    # - name: Extract PwnDrop
    #   command: tar -zxvf /pwndrop/pwndrop-linux-amd64.tar.gz -C /pwndrop
    # - name: Start PwnDrop
    #   command: /pwndrop/pwndrop-linux-amd64 -c /pwndrop/config.json &
    
    # - name: Configure firewall rules
    #   command: firewall-cmd --zone=public --add-port=3000/tcp --permanent
    #   become: yes
    
    # - name: Reload firewall rules
    #   command: firewall-cmd --reload
    #   become: yes
    
    # - name: Verify PwnDrop is Running
    #   command: curl http://localhost:3000/ping
    #   register: pwndrop_status
    #   failed_when: "'pong' not in pwndrop_status.stdout"
    
    # - name: Stop, install, start and check status of PwnDrop, stop again
    #   command:
    #     - /pwndrop/pwndrop stop
    #     - /pwndrop/pwndrop install
    #     - /pwndrop/pwndrop start
    #     - /pwndrop/pwndrop status
    #     - /pwndrop/pwndrop stop
    # - name: Clone password_cracking_rules, Hob0Rules and SecLists
    #   git:
    #     repo: https://github.com/NotSoSecure/password_cracking_rules.git
    #     dest: /opt/password_cracking_rules
    #   git:
    #     repo: https://github.com/praetorian-inc/Hob0Rules.git
    #     dest: /opt/Hob0Rules
    #   git:
    #     repo: https://github.com/danielmiessler/SecLists.git
    #     dest: /opt/SecLists
    # - name: Clone Probable-Wordlists
    #   git:
    #     repo: https://github.com/berzerk0/Probable-Wordlists.git
    #     dest: /opt/Probable-Wordlists        
    # - name: Download corporate.rule
    #   get_url:
    #     url: https://raw.githubusercontent.com/sparcflow/HackLikeALegend/master/corporate.rule
    #     dest: /opt/password_cracking_rules/corporate.rule
    # - name: Download rockyou-30000.rule
    #   get_url:
    #     url: https://raw.githubusercontent.com/hashcat/hashcat/master/rules/rockyou-30000.rule
    #     dest: /opt/password_cracking_rules/rockyou-30000.rule




